build: build.echo build.unique_id build.broadcast

build.echo:
	go build -o bin/echo cmd/echo/main.go

build.unique_id:
	go build -o bin/unique_id cmd/unique_id/main.go

build.broadcast:
	go build -o bin/broadcast cmd/broadcast/main.go
